// Command pkf is the pkfire CLI: a typed task runner that loads `Taskfile.pkl`
// and executes tasks with Bazel-style content-addressed caching.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/mizchi/pkfire/internal/cache"
	"github.com/mizchi/pkfire/internal/config"
	"github.com/mizchi/pkfire/internal/graph"
	"github.com/mizchi/pkfire/internal/hash"
	"github.com/mizchi/pkfire/internal/orchestrator"
	"github.com/mizchi/pkfire/internal/runner"
	"github.com/mizchi/pkfire/internal/watcher"
)

// version is overridden at link time via `-ldflags "-X main.version=…"`.
var version = "dev"

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "pkf:", err)
		os.Exit(1)
	}
}

func run(args []string, stdout, stderr io.Writer) error {
	if len(args) == 0 {
		usage(stdout)
		return nil
	}
	switch args[0] {
	case "version", "--version", "-v":
		fmt.Fprintln(stdout, version)
		return nil
	case "help", "--help", "-h":
		usage(stdout)
		return nil
	case "init":
		return cmdInit(args[1:], stdout, stderr)
	case "list":
		return cmdList(args[1:], stdout, stderr)
	case "graph":
		return cmdGraph(args[1:], stdout, stderr)
	case "run":
		return cmdRun(args[1:], stdout, stderr)
	default:
		usage(stderr)
		return fmt.Errorf("unknown command %q", args[0])
	}
}

func usage(w io.Writer) {
	fmt.Fprint(w, `pkf — pkfire task runner

usage:
  pkf <command> [args]

commands:
  init [-f FILE] [--force]              write a starter Taskfile.pkl
  run [-f FILE] [-j N] [--watch] [--dry-run] [--print-hash] [--no-cache] <task>
                                        run a task and its transitive deps
  list [-f FILE] [-v]                   list declared tasks (-v: cmd/deps)
  graph [-f FILE] [--format FMT] [--target TASK]
                                        emit DAG (formats: dot, mermaid)
  version                               print pkf version
  help                                  show this message

flags:
  -f, --file FILE        path to Taskfile.pkl (default: ./Taskfile.pkl)
  -j, --jobs N           max concurrent tasks (default: NumCPU)
      --watch            re-run on input changes (Ctrl+C to stop)
      --dry-run          print the execution plan and exit (no exec, no cache)
      --print-hash       print action keys for the target subgraph and exit
      --no-cache         disable cache lookup and store for this run
  -v, --verbose          (list only) include cmd preview and deps

cache directory:
  $PKFIRE_CACHE_DIR if set, otherwise $XDG_CACHE_HOME/pkfire (~/.cache/pkfire).
`)
}

func newFileFlag(fs *flag.FlagSet) *string {
	file := fs.String("f", "Taskfile.pkl", "path to Taskfile.pkl")
	fs.StringVar(file, "file", "Taskfile.pkl", "path to Taskfile.pkl")
	return file
}

// resolveFile turns the value of `-f` / `--file` into an absolute path.
// When the user did not specify the flag, this walks up from the current
// working directory looking for `Taskfile.pkl` in each ancestor — the
// same git/cargo discovery rule that lets `pkf run lint` work from any
// nested directory in a project. An explicit `-f` is taken at face value
// (filepath.Abs only).
func resolveFile(fs *flag.FlagSet, file string) (string, error) {
	if fileFlagWasSet(fs) {
		return filepath.Abs(file)
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return walkUp(cwd, file), nil
}

func fileFlagWasSet(fs *flag.FlagSet) bool {
	set := false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == "f" || f.Name == "file" {
			set = true
		}
	})
	return set
}

// walkUp returns the first ancestor (or `start` itself) that contains a
// regular file named `name`. If none exists up to the filesystem root,
// it falls back to the path joined against `start`, which the caller
// will subsequently fail to load with a clear "no such file" error.
func walkUp(start, name string) string {
	dir := start
	for {
		candidate := filepath.Join(dir, name)
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return filepath.Join(start, name)
		}
		dir = parent
	}
}

// initSkeleton renders the starter Taskfile `pkf init` writes. The
// amends URI tracks the running binary's version: a release-built
// binary (linked with `-X main.version=<ver>`) writes
// `package://…/pkfire@<ver>#/Taskfile.pkl`, while a dev binary
// (`version == "dev"`) writes the main-tracking HTTPS URL so users
// hacking on this repo's HEAD always get a resolvable amends.
func initSkeleton() string {
	return fmt.Sprintf(`/// Generated by `+"`pkf init`"+`. See https://github.com/mizchi/pkfire.
///
/// Author each task as a `+"`Task`"+` instance with a unique `+"`name`"+`, then
/// list it in the module-level `+"`tasks`"+`. Refer to other tasks with their
/// local binding (e.g. `+"`deps { build }`"+`) — typos are caught by Pkl
/// at evaluation time, before the runner ever starts.
amends %q

local hello = new Task {
  name = "hello"
  description = "Smoke task — replace with your own"
  cmd = "echo hello from pkfire"
}

tasks { hello }
`, schemaAmendsURI())
}

// schemaAmendsURI is the `amends` line `pkf init` writes. Released
// binaries pin to their own version's Pkl package; dev binaries fall
// back to the main HTTPS URL.
func schemaAmendsURI() string {
	if version == "dev" || version == "" {
		return "https://raw.githubusercontent.com/mizchi/pkfire/main/pkl/Taskfile.pkl"
	}
	return fmt.Sprintf("package://pkg.pkl-lang.org/github.com/mizchi/pkfire/pkfire@%s#/Taskfile.pkl", version)
}

func cmdInit(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("pkf init", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	file := newFileFlag(fs)
	force := fs.Bool("force", false, "overwrite an existing file")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if len(fs.Args()) > 0 {
		return fmt.Errorf("init takes no positional args, got %v", fs.Args())
	}
	if !*force {
		if _, err := os.Stat(*file); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", *file)
		}
	}
	if err := os.WriteFile(*file, []byte(initSkeleton()), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(stderr, "wrote %s\n", *file)
	fmt.Fprintf(stderr, "  next: pkf list      # see declared tasks\n")
	fmt.Fprintf(stderr, "        pkf run hello # smoke the generated example\n")
	return nil
}

func cmdList(args []string, stdout, _ io.Writer) error {
	fs := flag.NewFlagSet("pkf list", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	file := newFileFlag(fs)
	verbose := fs.Bool("v", false, "show cmd preview and deps")
	fs.BoolVar(verbose, "verbose", false, "show cmd preview and deps")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if len(fs.Args()) > 0 {
		return fmt.Errorf("list takes no positional args, got %v", fs.Args())
	}
	abs, err := resolveFile(fs, *file)
	if err != nil {
		return err
	}
	tf, err := config.Load(context.Background(), abs)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(tf.Tasks))
	for n := range tf.Tasks {
		names = append(names, n)
	}
	sort.Strings(names)
	if !*verbose {
		for _, n := range names {
			t := tf.Tasks[n]
			desc := ""
			if t.Description != nil {
				desc = "  — " + *t.Description
			}
			fmt.Fprintf(stdout, "%s%s\n", n, desc)
		}
		return nil
	}
	for i, n := range names {
		if i > 0 {
			fmt.Fprintln(stdout)
		}
		t := tf.Tasks[n]
		fmt.Fprintf(stdout, "%s\n", n)
		if t.Description != nil {
			fmt.Fprintf(stdout, "  desc: %s\n", *t.Description)
		}
		fmt.Fprintf(stdout, "  cmd:  %s\n", t.Cmd)
		if len(t.Deps) > 0 {
			fmt.Fprintf(stdout, "  deps: %s\n", strings.Join(t.Deps, ", "))
		}
		if !t.Cache {
			fmt.Fprintf(stdout, "  cache: disabled\n")
		}
	}
	return nil
}

func cmdGraph(args []string, stdout, _ io.Writer) error {
	fs := flag.NewFlagSet("pkf graph", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	file := newFileFlag(fs)
	format := fs.String("format", "dot", "output format: dot or mermaid")
	target := fs.String("target", "", "render only the subgraph rooted at this task")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if len(fs.Args()) > 0 {
		return fmt.Errorf("graph takes no positional args, got %v", fs.Args())
	}
	abs, err := resolveFile(fs, *file)
	if err != nil {
		return err
	}
	tf, err := config.Load(context.Background(), abs)
	if err != nil {
		return err
	}
	g, err := buildGraph(tf)
	if err != nil {
		return err
	}

	var nodes []string
	if *target != "" {
		if !g.Has(*target) {
			return fmt.Errorf("unknown task: %q", *target)
		}
		nodes, err = g.Subgraph(*target)
		if err != nil {
			return err
		}
	} else {
		nodes = g.Names()
	}
	keep := make(map[string]bool, len(nodes))
	for _, n := range nodes {
		keep[n] = true
	}

	switch *format {
	case "dot":
		return writeDOT(stdout, tf, nodes, keep)
	case "mermaid":
		return writeMermaid(stdout, tf, nodes, keep)
	default:
		return fmt.Errorf("unknown format %q (want: dot, mermaid)", *format)
	}
}

func writeDOT(w io.Writer, tf *config.Taskfile, nodes []string, keep map[string]bool) error {
	fmt.Fprintln(w, "digraph pkfire {")
	fmt.Fprintln(w, "  rankdir=LR;")
	fmt.Fprintln(w, `  node [shape=box, style="rounded,filled", fillcolor="#f8f8ff"];`)
	for _, n := range nodes {
		t := tf.Tasks[n]
		label := n
		if t.Description != nil {
			label = fmt.Sprintf("%s\\n%s", n, *t.Description)
		}
		fmt.Fprintf(w, "  %q [label=%q];\n", n, label)
	}
	for _, n := range nodes {
		for _, d := range tf.Tasks[n].Deps {
			if keep[d] {
				fmt.Fprintf(w, "  %q -> %q;\n", d, n)
			}
		}
	}
	fmt.Fprintln(w, "}")
	return nil
}

// mermaidIDReplacer turns task names into Mermaid-safe node IDs. The set
// of unsafe characters is conservative — only [A-Za-z0-9_] is accepted by
// the renderer in id positions.
var mermaidIDReplacer = strings.NewReplacer(
	":", "_", "-", "_", "/", "_", ".", "_", " ", "_",
)

func mermaidID(s string) string { return mermaidIDReplacer.Replace(s) }

func writeMermaid(w io.Writer, tf *config.Taskfile, nodes []string, keep map[string]bool) error {
	fmt.Fprintln(w, "flowchart LR")
	for _, n := range nodes {
		fmt.Fprintf(w, "  %s[%q]\n", mermaidID(n), n)
	}
	for _, n := range nodes {
		for _, d := range tf.Tasks[n].Deps {
			if keep[d] {
				fmt.Fprintf(w, "  %s --> %s\n", mermaidID(d), mermaidID(n))
			}
		}
	}
	return nil
}

func cmdRun(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("pkf run", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	file := newFileFlag(fs)
	printHash := fs.Bool("print-hash", false, "print action keys and exit")
	dryRun := fs.Bool("dry-run", false, "print the execution plan and exit")
	noCache := fs.Bool("no-cache", false, "disable cache for this run")
	watch := fs.Bool("watch", false, "re-run on input changes")
	jobs := fs.Int("j", 0, "max concurrent tasks (default: NumCPU)")
	fs.IntVar(jobs, "jobs", 0, "max concurrent tasks (default: NumCPU)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	rest := fs.Args()
	if len(rest) != 1 {
		return fmt.Errorf("run requires exactly one task name")
	}
	target := rest[0]

	abs, err := resolveFile(fs, *file)
	if err != nil {
		return err
	}
	ctx := context.Background()
	tf, err := config.Load(ctx, abs)
	if err != nil {
		return err
	}

	g, err := buildGraph(tf)
	if err != nil {
		return err
	}
	if !g.Has(target) {
		return fmt.Errorf("unknown task: %q", target)
	}
	order, err := g.Subgraph(target)
	if err != nil {
		return err
	}

	root := filepath.Dir(abs)
	switch {
	case *dryRun && *printHash:
		return fmt.Errorf("--dry-run and --print-hash are mutually exclusive")
	case *watch && (*dryRun || *printHash):
		return fmt.Errorf("--watch is incompatible with --dry-run / --print-hash")
	case *dryRun:
		return printDryRun(stdout, tf, order)
	case *printHash:
		return printHashes(stdout, root, tf, order)
	}

	var backend cache.Backend
	if !*noCache {
		dir, err := cache.DefaultDir()
		if err != nil {
			return fmt.Errorf("resolve cache dir: %w", err)
		}
		local := cache.New(dir)
		if remoteURL := os.Getenv("PKFIRE_REMOTE_CACHE"); remoteURL != "" {
			remote := cache.NewRemote(remoteURL, os.Getenv("PKFIRE_REMOTE_TOKEN"))
			backend = cache.NewLayered(local, remote)
		} else {
			backend = local
		}
	}
	r := runner.New(runner.Options{Workdir: root})
	orch := orchestrator.New(backend, r, stdout, stderr, orchestrator.Options{
		Parallelism: *jobs,
	})
	plan := &orchestrator.Plan{
		Order:      order,
		Tasks:      tf.Tasks,
		Defaults:   tf.Defaults,
		Root:       root,
		ConfigHash: hash.HashBytes(tf.Canonical),
	}
	if *watch {
		return runWatch(ctx, abs, root, target, orch, plan, stderr)
	}
	_, err = orch.Execute(ctx, plan)
	return err
}

// runWatch loops: execute the plan, then wait for input changes (or Ctrl+C),
// then re-execute. An in-flight run is cancelled when a fresh change lands so
// the user always sees results for the latest source state.
func runWatch(parentCtx context.Context, taskfilePath, root, target string, orch *orchestrator.Orchestrator, plan *orchestrator.Plan, stderr io.Writer) error {
	ctx, cancel := signal.NotifyContext(parentCtx, os.Interrupt, syscall.SIGTERM)
	defer cancel()

	paths := watchTargets(root, taskfilePath, plan)
	w, err := watcher.New(paths, 200*time.Millisecond)
	if err != nil {
		return fmt.Errorf("init watcher: %w", err)
	}
	defer w.Close()
	go w.Run(ctx)

	fmt.Fprintf(stderr, "[pkf] watching %d path(s) for %q (Ctrl+C to stop)\n", len(paths), target)

	for {
		runCtx, runCancel := context.WithCancel(ctx)
		done := make(chan error, 1)
		go func() {
			_, e := orch.Execute(runCtx, plan)
			done <- e
		}()

		err := <-done
		runCancel()
		if err != nil && !errors.Is(err, context.Canceled) {
			fmt.Fprintf(stderr, "[pkf] run failed: %v\n", err)
		}

		// Drop every event the run itself may have produced (output writes,
		// pkl evaluator scratch files, etc.) — only post-run edits should
		// count toward the next iteration.
		drain(w.Events())
		fmt.Fprintln(stderr, "[pkf] idle — waiting for changes")

		select {
		case <-w.Events():
			fmt.Fprintln(stderr, "[pkf] change detected — re-running")
		case <-ctx.Done():
			return nil
		}
	}
}

func drain(ch <-chan struct{}) {
	for {
		select {
		case <-ch:
		default:
			return
		}
	}
}

// watchTargets collects the set of filesystem paths whose changes should
// trigger a re-run: the Taskfile itself, every input glob's expansion, and
// (since glob expansion may miss new files) the workdir of each task.
func watchTargets(root, taskfilePath string, plan *orchestrator.Plan) []string {
	seen := map[string]struct{}{taskfilePath: {}}
	for _, name := range plan.Order {
		t := plan.Tasks[name]
		taskRoot := orchestrator.TaskRoot(t, plan.Root)
		seen[taskRoot] = struct{}{}
		entries, err := hash.HashInputs(taskRoot, t.Inputs)
		if err != nil {
			continue
		}
		for _, e := range entries {
			seen[filepath.Join(taskRoot, e.Path)] = struct{}{}
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	return out
}

func buildGraph(tf *config.Taskfile) (*graph.Graph, error) {
	nodes := make([]graph.Node, 0, len(tf.Tasks))
	for name, t := range tf.Tasks {
		nodes = append(nodes, graph.Node{Name: name, Deps: append([]string(nil), t.Deps...)})
	}
	return graph.Build(nodes)
}

// printHashes computes and prints the action key of every task in `order`.
// Cache state is not consulted; this is a diagnostic for understanding why
// a task does or does not hit cache.
func printHashes(stdout io.Writer, root string, tf *config.Taskfile, order []string) error {
	configHash := hash.HashBytes(tf.Canonical)
	for _, name := range order {
		task := tf.Tasks[name]
		taskRoot := orchestrator.TaskRoot(task, root)
		key, err := orchestrator.ComputeKey(task, tf.Defaults, taskRoot, configHash)
		if err != nil {
			return fmt.Errorf("compute key for %q: %w", name, err)
		}
		fmt.Fprintf(stdout, "%s\t%s\n", name, hash.FormatKey(key))
	}
	return nil
}

// printDryRun walks the plan in topological order and prints each task's
// cmd, deps, and cache disposition without running anything or touching
// the cache directory.
func printDryRun(stdout io.Writer, tf *config.Taskfile, order []string) error {
	for i, name := range order {
		t := tf.Tasks[name]
		fmt.Fprintf(stdout, "%d. %s\n", i+1, name)
		if t.Description != nil {
			fmt.Fprintf(stdout, "   desc: %s\n", *t.Description)
		}
		fmt.Fprintf(stdout, "   cmd:  %s\n", t.Cmd)
		if len(t.Deps) > 0 {
			fmt.Fprintf(stdout, "   deps: %s\n", strings.Join(t.Deps, ", "))
		}
		if !t.Cache {
			fmt.Fprintf(stdout, "   cache: disabled\n")
		}
		if t.Workdir != nil && *t.Workdir != "" {
			fmt.Fprintf(stdout, "   workdir: %s\n", *t.Workdir)
		}
	}
	return nil
}
